pipeline {
    agent any

    stages {
        stage('Checkout Codebase') {
            steps {
                checkout scm: [$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[credentialsId: 'wilbert-git-deployKeys', url: 'git@github.com:kerbaudisko21/slack-jenkins-go.git']]]
            }
        }

        stage('Build') {
            steps {
                echo 'Building Codebase'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Tests on changes'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Done!'
            }
        }
    }

    post {
        always {
            echo 'Sending Slack message'
            sh "go run send-jenkins-notification/slack-notification.go ${BUILD_URL} ${currentBuild.currentResult} ${BUILD_NUMBER} ${JOB_NAME} "
        }
    }
}
